import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",

//   icons: {
//     icon: "/favicon.svg",
//   },
// };


export const metadata: Metadata = {
  title: {
    default: "SkyCode – Cloud Code Editor",
    template: "%s | SkyCode",
  },

  description:
    "SkyCode is a powerful cloud-based code editor that lets developers write, run, and share code instantly. Supports multiple programming languages with real-time execution, secure cloud storage, and a modern developer-friendly interface.",

  keywords: [
    "SkyCode",
    "cloud code editor",
    "online IDE",
    "web code editor",
    "run code online",
    "JavaScript editor",
    "Python editor",
    "online compiler",
    "developer tools",
    "programming editor",
  ],

  authors: [
    {
      name: "Suman Kayal",
      url: "https://github.com/SUMANKAYALS",
    },
  ],

  creator: "Suman Kayal",

  metadataBase: new URL("https://skycode.dev"),

  openGraph: {
    title: "SkyCode – Cloud-Based Code Editor",
    description:
      "Write, run, and share code instantly with SkyCode. A fast and modern cloud IDE built for developers.",
    url: "https://skycode.dev",
    siteName: "SkyCode",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "SkyCode Cloud Editor",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "SkyCode – Cloud Code Editor",
    description:
      "Modern cloud-based code editor to write, run, and share code instantly.",
    images: ["/og-image.png"],
    creator: "@sumankayal",
  },

  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },

  robots: {
    index: true,
    follow: true,
  },

  category: "technology",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased antialiased min-h-screen bg-gradient-to-b from-gray-900 to-gray-950 text-gray-100 flex flex-col`}
        >
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>


          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
